### PR TITLE
feat: Move parser and plugin to peerDeps

### PR DESCRIPTION
**Pull request by Carter-Apas**

### CODE REVIEW

**Review by danieljimeneznz — CHANGES_REQUESTED** [review]
Why?

**Comment by Carter-Apas** [comment]
cause it should it actually be a peer dep as you need both of these in your package json to be used by your linter.

**Comment by danieljimeneznz** [comment]
> cause it should it actually be a peer dep as you need both of these in your package json to be used by your linter.

But by listing it as a dep it gets installed automatically when you install this package - listing it as a peerdep requires me to list these two packages in my `package.json`: https://sergioviniciuss.medium.com/how-do-peerdependencies-work-837d0ff8f63f

https://github.com/standard/eslint-config-standard/issues/107

^In a public shared eslint-config:

> I'd love to do this, but eslint shareable configs (which is what this package is) cannot contain executable code. It's just exporting a JavaScript object from a JSON file.
> 
> The user of the config is responsible for installing ESLint, the appropriate plugin dependencies, and instantiating ESLint with them.

However we never really share this externally and it just gets annoying to list the plugin dep everytime + we have to ensure that eslint is compatible with the version of eslint-config. I'm not sure this PR would solve the current problem you're facing?

**Comment by Carter-Apas** [comment]
In the config you shared typescript parser nor plugin exist, because as they state it is a shareable config which only contains json. We should then according to the article remove both of these packages.

**Review by danieljimeneznz — APPROVED** [review]

**Pull request merged**
